config/routes.rb
UniversityApp::Application.routes.draw do  
=begin
  get "teachers/index"

  get "teachers/new"

  get "teachers/create"

  get "teachers/show"

  get "teachers/edit"

  get "teachers/update"

  get "teachers/destroy"
=end
	root :to => 'university#index' 
  resources :students
  resources :teachers
  
	
=begin  get "students/show"	
  
  get "students/edit"

  get "students/delete"

  get "students/update"
=end

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name, :program, :teacher
end

app/models/name.rb
class Name < ActiveRecord::Base
  attr_accessible :course, :term
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :faculty, :name
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
  attr_accessible :exam, :qualif, :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :addres, :age, :cellphone, :identification, :name, :progam
  
  validates :name, :identification, :progam, :presence => true
  validates :age, :numericality => {:greater_than => 0, :less_than => 120}
  
  validates :cellphone, :length => {:is => 10}
  
  
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  attr_accessible :address, :cellphone, :email, :name, :profession, :identification, :area_teacher
  
  validates :name, :identification, :address, :cellphone, :profession, :presence => true 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, format: { with: VALID_EMAIL_REGEX }, :uniqueness => true
  validates :identification, :numericality => true
  validates :cellphone, :length => {:is => 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
     @student = Student.all
  end  
  
  def new    
    @student = Student.new
  end
 
  def create
    @student = Student.new(params[:student])
    if @student.save
      # Handle a successful save.
      flash[:success] = "added student successfully"
      @student = Student.all
      render 'index'      
    else     
      render 'new'
    end
  end
  
  def show
	   @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      # Handle a successful save.
      flash[:notice] = "updated #{@student.name} successfully"  
      redirect_to students_path                    
    else
      flash[:error] = "can't update #{@student.name}"
      redirect_to edit_student_path
    end
  end
    
  def destroy
    Student.find(params[:id]).destroy
    flash[:notice] = "deleted successfully"
    redirect_to students_path
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teacher = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(params[:teacher])
    if @teacher.save
      # Handle a successful save.
      flash[:success] = "added teacher successfully"
      @teacher = Teacher.all
      render 'index'      
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(params[:teacher])
      flash[:notice] = "updated #{@teacher.name} successfully"  
      redirect_to teacher_path
    else
      flash[:error] = "can't update #{@teacher.name}"
      redirect_to edit_teacher_path
    end
  end

  def destroy
  end
end

app/controllers/university_controller.rb
class UniversityController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by ljrzarate
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "University", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Students", students_path %></li>
          <li><%= link_to "Teachers", teachers_path%></li>
          <li><%= link_to "Courses", '#' %></li>
          <li><%= link_to "Exams", '#' %></li>
          <li><%= link_to "Qualifications", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University</title>
	
	<%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
   <%= render 'layouts/header'%>
    <div class="container">
    	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>	
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<%if @student != nil
	 instance = @student
	else
		instance = @teacher
	end %>
<% if instance.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(instance.errors.count, "error") %>.
    </div>
    <ul>
    <% instance.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@student) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :identification %>
      <%= f.text_field :identification %>

      <%= f.label :age %>
      <%= f.text_field :age %>

      <%= f.label :addres %>
      <%= f.text_field :addres%>
      
      <%= f.label :cellphone %>
      <%= f.text_field :cellphone%>
      
      <%= f.label :progam %>
      <%= f.text_field :progam%>

      <%= f.submit "Update Student", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<h1>Listing Students</h1>
<%= link_to 'New Student', new_student_path %>
<table class="table table-striped">
  <tr>
    <th>Identification</th>
    <th>Name</th>
    <th>age</th>
    <th>program</th>
    <th>address</th>
    <th>cellphone</th>
    <th>Edit</th>
  </tr>

<%@student.each do |student|%>
  <tr>
    <td><%= student.identification%></td>
    <td><%= student.name%></td>
    <td><%= student.age%></td>
    <td><%= student.progam%></td>
    <td><%= student.addres%></td>
    <td><%= student.cellphone%></td>
    <td><%= link_to 'Edit Student', edit_student_path(student)%> |
    	<%=link_to 'Delete Student', student_path(student), :method => "delete", :confirm => "Are you sure?"%>
    </td>    
  </tr>
<% end %>
</table>



app/views/students/new.html.erb
<h1>New Student</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@student) do |f| %>
		
	  <%= render 'shared/error_messages' %>
	  		
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :identification %>
      <%= f.text_field :identification %>

      <%= f.label :age %>
      <%= f.text_field :age %>

      <%= f.label :addres %>
      <%= f.text_field :addres%>
      
      <%= f.label :cellphone %>
      <%= f.text_field :cellphone%>
      
      <%= f.label :progam %>
      <%= f.text_field :progam%>

      <%= f.submit "Create Student", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<h1><%=@student.name%></h1>
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/students/update.html.erb
<h1>Info of <%= @student.name.capitalize%></h1>
<div class="row">
	<div class="span6 offset3">
		<form class="well">
			<label>Identificacion: <%= @student.identification%></label>			
			<label>Age: <%= @student.age%></label>
			<label>Program: <%= @student.progam%></label>
			<label>Address: <%= @student.addres%></label>
			<label>Cellphone: <%= @student.cellphone%></label>			
			<button type="back" class="btn" action ="/students">
				Back
			</button>
		</form>
	</div>
</div>

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/destroy.html.erb
<h1>Teachers#destroy</h1>
<p>Find me in app/views/teachers/destroy.html.erb</p>

app/views/teachers/edit.html.erb
<h1>New Teacher</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@teacher) do |f| %>
		
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :identification %>
		<%= f.text_field :identification %>

		<%= f.label :profession %>
		<%= f.text_field :profession %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :addres %>
		<%= f.text_field :address%>

		<%= f.label :cellphone %>
		<%= f.text_field :cellphone%>

		<%= f.label :area_teacher %>		
		<%= select_tag(:area_teacher, options_for_select([['---'],['Mathematics'], ['Software'], ['Networking']])) %>
				

		<%= f.submit "Create Teacher", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/teachers/index.html.erb
<h1>Listing Teacher</h1>
<%= link_to 'New Teacher', new_teacher_path %>
<table class="table table-striped">
  <tr>
    <th>Identification</th>
    <th>Name</th>
    <th>profession</th>
    <th>email</th>
    <th>area</th>
    <th>cellphone</th>
    <th>address</th>
    <th>Edit</th>
  </tr>

<%@teacher.each do |teacher|%>
  <tr>
    <td><%= teacher.identification%></td>
    <td><%= teacher.name%></td>
    <td><%= teacher.profession%></td>
    <td><%= teacher.email%></td>
    <td><%= teacher.area_teacher%></td>
    <td><%= teacher.cellphone%></td>
    <td><%= teacher.address%></td>    
    <td><%= link_to 'Edit Teacher', edit_teacher_path(teacher)%> |
    	<%=link_to 'Delete Teacher', teacher_path(teacher), :method => "delete", :confirm => "Are you sure?"%>
    </td>    
  </tr>
<% end %>
</table>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@teacher) do |f| %>
		
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :identification %>
		<%= f.text_field :identification %>

		<%= f.label :profession %>
		<%= f.text_field :profession %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :addres %>
		<%= f.text_field :address%>

		<%= f.label :cellphone %>
		<%= f.text_field :cellphone%>

		<%= f.label :area_teacher %>		
		<%= select_tag(:area_teacher, options_for_select([['---'],['Mathematics'], ['Software'], ['Networking']])) %>
				

		<%= f.submit "Create Teacher", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/teachers/show.html.erb
<h1>Teachers#show</h1>
<p>Find me in app/views/teachers/show.html.erb</p>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>

app/views/university/index.html.erb
<h1>University#index</h1>
<p>Find me in app/views/university/index.html.erb</p>